### ISSUE TITLE
Don't return 0 when an error occurs

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-elastixWrapper#4]
The application returns 0 (which means no error occured), even when something went wrong.
See:

``` bash
(cluster_env37) pape@gpu6:~/Work/my_projects/dev-platy/test/registration$ /g/almf/software/Fiji.app/ImageJ-linux64 --ij2 --headless --run Transformix elastix_directory=/g/almf/software/elastix_v4.8 workingDirectory=tmp_registration/work_dir0 inputImageFile=/g/kreshuk/pape/Work/my_projects/platy-browser-data/stomach_prospr_target.xml transformationFile=/g/kreshuk/pape/Work/my_projects/platy-browser-data/registration/0.0.0/transformations/0.0.0/TransformParameters.Affine-3Channels.0.txt outputFile=/g/kreshuk/pape/Work/my_projects/platy-browser-data/stomach_prospr_target_registered outputModality='Save as BigDataViewer .xml/.h5' numThreads=1
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Unsupported format or not found
Unsupported format or not found
Unsupported format or not found
Unsupported format or not found
Unsupported format or not found
Unsupported format or not found
[ERROR] null
java.lang.IllegalArgumentException: Invalid character at index 19
        at org.scijava.parse.Position.die(Position.java:70)
        at org.scijava.parse.ExpressionParser$ParseOperation.parsePostfix(ExpressionParser.java:210)
        at org.scijava.parse.ExpressionParser.parsePostfix(ExpressionParser.java:113)
        at org.scijava.parse.eval.AbstractEvaluator.evaluate(AbstractEvaluator.java:87)
        at org.scijava.parse.DefaultParseService$ItemsList.parseItems(DefaultParseService.java:105)
        at org.scijava.parse.DefaultParseService$ItemsList.<init>(DefaultParseService.java:73)
        at org.scijava.parse.DefaultParseService.parse(DefaultParseService.java:59)
        at org.scijava.parse.ParseService.parse(ParseService.java:57)
        at org.scijava.run.console.RunArgument.lambda$handle$0(RunArgument.java:89)
        at org.scijava.startup.DefaultStartupService.executeOperations(DefaultStartupService.java:69)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:107)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
(cluster_env37) pape@gpu6:~/Work/my_projects/dev-platy/test/registration$ echo $?
0
```

**Comment by constantinpape** [comment]
Fixed in recent commit.
